### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by terrorist96** [DVDAndroid/XposedInstaller#34] opened 2016-02-04 03:37 UTC
So this replaces the standard xposed installer apk? I'm supposed to uninstall that prior to installing this? Will I lose my modules if I uninstall the standard xposed installer? Why doesn't rovo89 use this installer to replace his old/outdated one?

**Comment by ja-som** [comment] 2016-02-04 05:23
Yes, yes, no, rovos version is not outdated, it only does not have material design and few features, he don't want it now, maybe once :)

**Comment by DVDAndroid** [comment] 2016-02-04 05:46
Excellent answer @ja-som.
You will not lose any module, but you need to activate again.

I close the issue, for other questions, @terrorist96 feel free to reopen it.

**Comment by terrorist96** [comment] 2016-02-04 14:24
One more question: why don't you put this on Google play so it's easy to receive updates instead of checking the xda thread occasionally to check for updates?

**Comment by ElTifo** [comment] 2016-02-04 14:28
The update should appear on the app itself. There's no need for Google
play. At least rovo's original app version does check for it's updates. I
believe this one does it as well.
Em 04/02/2016 2:24 da tarde, "terrorist96" notifications@github.com
escreveu:

**Comment by terrorist96** [comment] 2016-02-04 14:34
Also, this issue in the standard installer is also present in this version too. https://github.com/rovo89/XposedInstaller/issues/256

**Comment by DVDAndroid** [comment] 2016-02-04 15:33
I will never publish this app in google play because it's a fork and if rovo89 didn't pushed this app in the store, I will not do it.

Thanks for reporting Gmail issue

**Comment by terrorist96** [comment] 2016-02-05 02:54
No problem. Another thing: I have the Nexus 6p, which is 64 bit, but when I open the framework section, it defaults to showing the arm version, not the arm 64 bit version. Is this a bug?

**Comment by DVDAndroid** [comment] 2016-02-05 05:40
It's not a bug, I already added auto selection of right framework in issue-25 branch

**Comment by terrorist96** [comment] 2016-02-05 05:42
Ah, okay, so it'll be fixed in an upcoming update then. Thanks!

**Comment by terrorist96** [comment] 2016-02-05 14:37
Bug: experimental is set as my global default setting, but it won't show that. For example, the following module won't display the fact that it has an update and when I select it, it says there's a test version available but it isn't shown due to my settings. 

http://repo.xposed.info/module/com.stirante.storeprefs

**Comment by DVDAndroid** [comment] 2016-02-05 14:39
Also fixed it in next release. At the moment, I'm trying to fix gmail bug, but without success

**Comment by terrorist96** [comment] 2016-02-05 14:42
Thanks! Will I get notified within the app about the update when you release it? 
Also, did you look at the answer given here for the Gmail issue:
http://stackoverflow.com/questions/26883259/gmail-5-0-app-fails-with-permission-denied-for-the-attachment-when-it-receives/

**Comment by DVDAndroid** [comment] 2016-02-05 14:47
Yes. Thanks for the help

**Comment by terrorist96** [comment] 2016-02-05 14:49
Also, this probably isn't an issue on your end, but maybe it is. When I have the Flat Style Colored Bars module active and I try to open a link from within the installer, the top bar is pure white and I can't see the X button on the top left or the menu button on the top right. I reported it to the module dev already, but thought I'd mention it here too. Thanks for all you do! 

http://repo.xposed.info/module/com.bocharov.xposed.fscb

**Comment by DVDAndroid** [comment] 2016-02-06 14:22
I've tested flat style colored bars and I have no problem. 
Gmail bug is now fixed. If bug persist you need to grant storage permission of gmail if you are on 6.0

**Closed as completed by DVDAndroid** 2016-02-06 14:22 UTC
Labels: question

**Comment by terrorist96** [comment] 2016-02-06 14:38
https://youtu.be/3U9ILManys4

**Comment by DVDAndroid** [comment] 2016-02-06 14:40
Theme? Black/Dark?
Color?

Do you have modified some options in the module?

Probably it's a module bug

**Comment by terrorist96** [comment] 2016-02-06 15:19
Theme is Black, but it still happens on Light and Dark themes too. Setting the color to the default blue doesn't fix it either.

Regarding the FSCB module, the only option I have changed is Allow custom colors when the keyboard is open. But the problem goes away for me when I disable FSCB, so it's strange that you don't have the issue when you activate FSCB.
I have a Nexus 6p btw.
